In [81]:
import pandas as pd
pd.set_option('display.max_rows', None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [82]:
def clean_quantity(row):
    if pd.isna(row) or row == 'NaN':
        return None, None
    
    # Virgülü noktaya çevir (1,5 -> 1.5)
    row = str(row).replace(',', '.')
    
    # Regex ile sayısal kısmı ve birimi ayır
    # İlk sayısal grubu (ondalık dahil) ve sonrasındaki harf grubunu yakalar
    match = re.search(r"(\d+\.?\d*)\s*([a-zA-Zğüşıöç]+)?", row, re.IGNORECASE)
    
    if match:
        value = match.group(1)
        unit = match.group(2).lower() if match.group(2) else None
        
        # Birim standardizasyonu
        unit_map = {
            'ml': 'ml', 'l': 'l', 'g': 'g', 'kg': 'kg', 
            'grammes': 'g', 'gr': 'g', 'cl': 'cl'
        }
        unit = unit_map.get(unit, unit)
        
        return float(value), unit
    return None, None

def clean_categories(text):
    if pd.isna(text):
        return []
    
    # 1. Adım: Virgülleri ve boşlukları temizle
    # Virgüllere göre böl, her parçanın başındaki/sonundaki boşluğu sil
    parts = [part.strip() for part in text.split(',')]
    
    # 2. Adım: Sadece içi dolu olan (boş olmayan) kelimeleri tut
    clean_list = [p for p in parts if p and p != '']
    
    return clean_list

In [83]:
data = pd.read_csv('/Users/oguzhanerbil/Documents/Repolarım/food-health-predictor/data/ham_data.csv')

In [84]:
data.head()

,url,barkod,urun_adi,miktar,ambalaj,markalar,kategoriler,etiketler,mensei,uretim_yerleri,...,nutriscore_puan,ns_negatif_puan,ns_pozitif_puan,ns_enerji_puan,ns_seker_puan,ns_doymus_yag_puan,ns_tuz_puan,ns_protein_puan,ns_lif_puan,ns_meyve_sebze_baklagil_puan
0,https://world.openfoodfacts.org/product/611124...,6111246721261,Fromage Blanc Nature – Milky Food Professional...,1 kg,Plastic,Milky Food Professional,"Dairies, ,, Fermented foods, ,, Fermented milk...",Vegetarian,Maroc,Maroc,...,-2.0,1.0,3.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0
1,https://world.openfoodfacts.org/product/611103...,6111035000430,sidi ali – سيدي علي – 33 cl,33 cl,"Plastic, ,, Bottle",سيدي علي,"Beverages and beverages preparations, ,, Bever...",NaN,NaN,NaN,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,https://world.openfoodfacts.org/product/611103...,6111035000058,"Eau minérale naturelle – sidi ali – 1,5 L","1,5 L","Plastic, ,, Bottle or vial, ,, Bottle",sidi ali,"Beverages and beverages preparations, ,, Bever...","ISO 22000, ,, ISO 14001, ,, ISO 45001, ,, ISO ...",Morocco,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,https://world.openfoodfacts.org/product/611103...,6111035002175,Sidi Ali – 2 L,2 L,NaN,Sidi Ali,"Beverages and beverages preparations, ,, Bever...",Green Dot,"Bassin d'Oulmès, ,, Sidi Ali Cherif",NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,https://world.openfoodfacts.org/product/327408...,3274080005003,Eau De Source – Cristaline – 1500 ml,1500 ml,"Aluminium-can, ,, HdpeFilm-packet, ,, PpFilm-w...",Cristaline,"Beverages and beverages preparations, ,, Bever...",Triman,France,"Saint-Martin de Gurson, ,, France, ,, 24610",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
data["urun_bilgisi"] = data["urun_adi"].str.split("–").str[0].str.strip()

data[['miktar', 'birim']] = data['miktar'].apply(
    lambda x: pd.Series(clean_quantity(x))
)

data['kategori_listesi'] = data['kategoriler'].apply(clean_categories)
data['etiketler_listesi'] = data['etiketler'].apply(clean_categories)

data['alerjenler'] = data['alerjenler'].apply(clean_categories)
data['eser_miktarlar'] = data['eser_miktarlar'].apply(lambda x: [item.strip() for item in str(x).split(',')] if pd.notna(x) else [])

data['markalar'] = data['markalar'].apply(lambda x: str(x).split(',')[0].strip() if pd.notnull(x) else x)
data['markalar'] = data['markalar'].apply(lambda x: str(x).split(',')[0].strip().lower() if pd.notnull(x) else x)

In [86]:
data[data["yesil_skor_notu"].isna()].head()

,url,barkod,urun_adi,miktar,ambalaj,markalar,kategoriler,etiketler,mensei,uretim_yerleri,...,ns_seker_puan,ns_doymus_yag_puan,ns_tuz_puan,ns_protein_puan,ns_lif_puan,ns_meyve_sebze_baklagil_puan,urun_bilgisi,birim,kategori_listesi,etiketler_listesi
1,https://world.openfoodfacts.org/product/611103...,6111035000430,sidi ali – سيدي علي – 33 cl,33.0,"Plastic, ,, Bottle",سيدي علي,"Beverages and beverages preparations, ,, Bever...",NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,sidi ali,cl,"[Beverages and beverages preparations, Beverag...",[]
2,https://world.openfoodfacts.org/product/611103...,6111035000058,"Eau minérale naturelle – sidi ali – 1,5 L",1.5,"Plastic, ,, Bottle or vial, ,, Bottle",sidi ali,"Beverages and beverages preparations, ,, Bever...","ISO 22000, ,, ISO 14001, ,, ISO 45001, ,, ISO ...",Morocco,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,Eau minérale naturelle,l,"[Beverages and beverages preparations, Beverag...","[ISO 22000, ISO 14001, ISO 45001, ISO 9001]"
3,https://world.openfoodfacts.org/product/611103...,6111035002175,Sidi Ali – 2 L,2.0,NaN,sidi ali,"Beverages and beverages preparations, ,, Bever...",Green Dot,"Bassin d'Oulmès, ,, Sidi Ali Cherif",NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,Sidi Ali,l,"[Beverages and beverages preparations, Beverag...",[Green Dot]
4,https://world.openfoodfacts.org/product/327408...,3274080005003,Eau De Source – Cristaline – 1500 ml,1500.0,"Aluminium-can, ,, HdpeFilm-packet, ,, PpFilm-w...",cristaline,"Beverages and beverages preparations, ,, Bever...",Triman,France,"Saint-Martin de Gurson, ,, France, ,, 24610",...,0.0,0.0,0.0,0.0,0.0,0.0,Eau De Source,ml,"[Beverages and beverages preparations, Beverag...",[Triman]
5,https://world.openfoodfacts.org/product/611112...,6111128000071,Ain Saïss – Danone – 1.5 l,1.5,Plastic bottle,danone,"Beverages and beverages preparations, ,, Bever...",NaN,Morocco,Fes Morocco,...,0.0,0.0,0.0,0.0,0.0,0.0,Ain Saïss,l,"[Beverages and beverages preparations, Beverag...",[]

In [87]:
data[["miktar","birim"]].head()

   miktar birim
0     1.0    kg
1    33.0    cl
2     1.5     l
3     2.0     l
4  1500.0    ml

In [88]:
data.isnull().mean() * 100

url                              0.000000
barkod                           0.000000
urun_adi                         0.000000
miktar                          10.957223
ambalaj                         43.004909
markalar                         2.507013
kategoriler                      0.000000
etiketler                       19.512623
mensei                          59.256662
uretim_yerleri                  69.652875
satildigi_ulkeler                0.035063
icerik_metni                     5.855540
alerjenler                       0.000000
eser_miktarlar                   0.000000
icerik_sayisi                    6.206171
nutriscore_notu                  0.245442
nova_grubu                      11.115007
yesil_skor_notu                 26.858345
palmiye_yagi_icermez             9.344320
vejetaryen                      13.990182
vegan_durumu                     6.030856
yag_seviyesi                     4.242637
doymus_yag_seviyesi              4.996494
seker_seviyesi                   4.996494
tuz_seviyesi                     2.857644
enerji_kj                        3.260870
enerji_kcal                      3.190743
yag_g                            3.208275
doymus_yag_g                     3.997195
karbonhidrat_g                   3.278401
seker_g                          3.962132
lif_g                           19.950912
protein_g                        3.208275
tuz_g                            1.840813
sodyum_g                         4.067321
alkol_yuzde                     93.267882
meyve_sebze_baklagil_yuzde      73.825386
nutriscore_puan                  0.245442
ns_negatif_puan                  0.245442
ns_pozitif_puan                  0.245442
ns_enerji_puan                  13.586957
ns_seker_puan                    0.245442
ns_doymus_yag_puan              13.586957
ns_tuz_puan                      0.245442
ns_protein_puan                  0.859046
ns_lif_puan                      0.245442
ns_meyve_sebze_baklagil_puan     0.245442
urun_bilgisi                     0.000000
birim                           12.903226
kategori_listesi                 0.000000
etiketler_listesi                0.000000
dtype: float64

In [89]:
data.drop(columns=["sodyum_g","enerji_kj","yag_seviyesi","doymus_yag_seviyesi","seker_seviyesi","tuz_seviyesi","url","urun_adi","kategoriler","etiketler","ambalaj","mensei","uretim_yerleri","satildigi_ulkeler","icerik_metni","urun_bilgisi","nutriscore_puan","ns_negatif_puan","ns_pozitif_puan","ns_enerji_puan","ns_seker_puan","ns_doymus_yag_puan","ns_tuz_puan","ns_protein_puan","ns_lif_puan","ns_meyve_sebze_baklagil_puan"], inplace=True)

In [90]:
data["etiketler_listesi"].head(20)

0                                          [Vegetarian]
1                                                    []
2           [ISO 22000, ISO 14001, ISO 45001, ISO 9001]
3                                           [Green Dot]
4                                              [Triman]
5                                                    []
6                                                    []
7                                                    []
8                                    [Green Dot, Maroc]
9                                                    []
10                                          [Green Dot]
11    [French milk, Made in France, Nutriscore, Nutr...
12    [Fair trade, Source of fibre, High fibres, Mad...
13    [Vegetarian, Fair trade, No gluten, Organic, C...
14    [ISO 22000, ISO 14001, ISO 45001, ISO 9001, Na...
15    [Sustainable, No preservatives, Source of fibr...
16    [No gluten, No preservatives, FSC, Green Dot, ...
17                                                   []
18                      [Vegetarian, Green Dot, Triman]
19                                                   []
Name: etiketler_listesi, dtype: object

In [91]:
for column in data.columns:
    unique_values = data[column].astype(str).unique()
    unique_values_str = sorted(list(unique_values))
    n = 10
    displayed_values = unique_values_str[:n]
    print(f"{column} ({len(unique_values_str)}): {displayed_values}{' ...' if len(unique_values_str) > n else ''}")

barkod (5704): ['10001219', '10001400', '10015599', '10089149', '10096376', '10100295', '10217603', '10254899', '10677964', '11110016508'] ...
miktar (321): ['0.0', '0.07', '0.095', '0.1', '0.112', '0.125', '0.14', '0.15', '0.18', '0.2'] ...
markalar (1762): ['07x netto 03.25', '10dh', '166', '2keep', '365 whole foods market', '3bears', '5 fruits', '7 up', 'abatilles', "abbot kinney's"] ...
alerjenler (305): ["['Apple', 'Gluten', 'Gluten', 'Gluten']", "['Apple', 'Milk', 'Milk']", "['Apple']", "['Avoine']", "['Banana']", "['Beef', 'Gluten', 'Milk', 'Pork', 'Sulphur dioxide and sulphites']", "['Beef', 'Gluten', 'Sesame seeds', 'Soybeans']", "['Beef', 'Milk', 'Pork']", "['Beef']", "['Celery', 'Chicken', 'Eggs', 'Gluten', 'Milk', 'Soybeans']"] ...
eser_miktarlar (478): ["['Agua']", "['Basil-oil', 'Pesticides']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Lupin', 'Milk', 'Molluscs', 'Mustard', 'Nuts', 'Peanuts', 'Sesame seeds', 'Soybeans', 'Sulphur dioxide and sulphites']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Lupin', 'Milk', 'Molluscs', 'Mustard', 'Soybeans']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Lupin', 'Milk', 'Molluscs', 'Soybeans']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Milk', 'Molluscs', 'Mustard', 'Sesame seeds', 'Soybeans']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Milk', 'Molluscs', 'Mustard', 'Soybeans']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Milk', 'Molluscs', 'Mustard']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Milk', 'Molluscs', 'Nuts', 'Sesame seeds', 'Soybeans']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Milk', 'Molluscs', 'Soybeans']"] ...
icerik_sayisi (72): ['1.0', '10.0', '101.0', '107.0', '11.0', '12.0', '13.0', '14.0', '15.0', '150.0'] ...
nutriscore_notu (6): ['A', 'B', 'C', 'D', 'E', 'nan']
nova_grubu (5): ['1.0', '2.0', '3.0', '4.0', 'nan']
yesil_skor_notu (6): ['A', 'B', 'C', 'D', 'E', 'nan']
palmiye_yagi_icermez (3): ['False', 'True', 'nan']
vejetaryen (3): ['False', 'True', 'nan']
vegan_durumu (4): ['maybe', 'nan', 'no', 'yes']
enerji_kcal (618): ['0.0', '1.0', '10.0', '100.0', '101.0', '102.0', '1023.0', '103.0', '104.0', '105.0'] ...
yag_g (658): ['-0.880969080882353', '0.0', '0.0001', '0.0005', '0.01', '0.02', '0.03', '0.033', '0.039', '0.04'] ...
doymus_yag_g (439): ['-0.126229194852941', '0.0', '0.0001', '0.001', '0.0021', '0.0047945625', '0.005', '0.006', '0.006567', '0.007'] ...
karbonhidrat_g (867): ['0.0', '0.0001', '0.001', '0.01', '0.016', '0.028', '0.029', '0.1', '0.125', '0.2'] ...
seker_g (451): ['0.0', '0.0001', '0.01', '0.017', '0.029', '0.03', '0.05', '0.08', '0.1', '0.10000000149012'] ...
lif_g (485): ['0.0', '0.00075', '0.00629', '0.01', '0.014642265625', '0.04', '0.040909375', '0.046', '0.05', '0.053'] ...
protein_g (630): ['0.0', '0.0001', '0.001', '0.03', '0.038', '0.046', '0.05', '0.06', '0.07', '0.083'] ...
tuz_g (755): ['0.0', '0.0001', '0.000145', '0.00015', '0.0001625', '0.0001875', '0.0001964285714285', '0.0002', '0.00022', '0.000225'] ...
alkol_yuzde (33): ['0.0', '0.229', '0.5', '1.2', '12.0', '13.8', '17.0', '22.0', '23.0', '24.0'] ...
meyve_sebze_baklagil_yuzde (388): ['0.0', '0.00128173828125', '0.0050438774956589', '0.0099609375', '0.01', '0.0117710658482153', '0.0126429966517847', '0.0239246890419409', '0.0394775390625001', '0.0395833333333334'] ...
birim (53): ['None', 'b', 'biscuits', 'bo', 'bolsitas', 'box', 'calibre', 'cl', 'doigts', 'eggs'] ...
kategori_listesi (3271): ['["Aliments d\'origine végétale", \'Aliments et boissons à base de végétaux\', \'Céréales et dérivés\', \'Céréales et pommes de terre\', \'Céréales extrudées\', \'Céréales pour petit déjeuner riches en fibres\', \'Céréales pour petit-déjeuner\', \'Petit-déjeuners\']', '["fr:Flocons d\'avoine ( gros)"]', "['A', 'fr:Cruesli']", "['Alimentos de origen vegetal', 'Alimentos de origen vegetal en conserva', 'Alimentos y bebidas de origen vegetal', 'Cereales en conserva', 'Cereales y derivados', 'Cereales y patatas', 'Conservas', 'Frutas y verduras y sus productos', 'Maíz dulce en conserva', 'Maíz en conserva', 'Vegetables - Prepared/Processed (Shelf Stable)', 'Verduras y hortalizas en conserva', 'Verduras y hortalizas y sus productos']", "['Aliments et boissons à base de végétaux', 'Boissons', 'Boissons aux fruits', 'Boissons avec sucre ajouté', 'Boissons plates aux fruits', 'Boissons sans alcool', 'Boissons à base de végétaux']", "['Bakkerij', 'Crackers', 'Beschuit']", "['Bean waffles']", "['Bebidas', 'Bebidas lácteas proteicas', 'Bebidas proteicas', 'Leches', 'Leches chocolatadas', 'Leches saborizadas', 'Lácteos']", "['Bebidas', 'Bebidas proteicas', 'Bebidas sabor vainilla', 'Bebidas saborizadas']", "['Beverages and beverages preparations', 'Beverage preparations', 'Herbal teas', 'Herbal teas in tea bags']"] ...
etiketler_listesi (3056): ['["fr:Convient pour l\'alimentation des nourrissons"]', '["fr:Médaille d\'or Paris 1994"]', '["fr:Saveurs en\'Or", \'fr:Sans nitrate\']', "['1 of 5 a day']", "['100% arabica']", "['100% muscle', 'Nutriscore', 'Nutriscore Grade A']", "['100% natural', 'French milk', 'Green Dot', 'New recipe', 'Nutriscore', 'Nutriscore Grade A']", "['100% natural', 'Green Dot', 'Tidy man']", "['100% natural', 'Nutriscore', 'Nutriscore Grade A']", "['100% natural']"] ...

In [92]:
data["palmiye_yagi_icermez"].value_counts()

palmiye_yagi_icermez
True     4385
False     786
Name: count, dtype: int64

In [93]:
data.isnull().mean() * 100

barkod                         0.000000
miktar                        10.957223
markalar                       2.507013
alerjenler                     0.000000
eser_miktarlar                 0.000000
icerik_sayisi                  6.206171
nutriscore_notu                0.245442
nova_grubu                    11.115007
yesil_skor_notu               26.858345
palmiye_yagi_icermez           9.344320
vejetaryen                    13.990182
vegan_durumu                   6.030856
enerji_kcal                    3.190743
yag_g                          3.208275
doymus_yag_g                   3.997195
karbonhidrat_g                 3.278401
seker_g                        3.962132
lif_g                         19.950912
protein_g                      3.208275
tuz_g                          1.840813
alkol_yuzde                   93.267882
meyve_sebze_baklagil_yuzde    73.825386
birim                         12.903226
kategori_listesi               0.000000
etiketler_listesi              0.000000
dtype: float64

In [94]:
data.to_csv('/Users/oguzhanerbil/Documents/Repolarım/food-health-predictor/data/data.csv', index=False)

In [95]:
data.columns

Index(['barkod', 'miktar', 'markalar', 'alerjenler', 'eser_miktarlar',
       'icerik_sayisi', 'nutriscore_notu', 'nova_grubu', 'yesil_skor_notu',
       'palmiye_yagi_icermez', 'vejetaryen', 'vegan_durumu', 'enerji_kcal',
       'yag_g', 'doymus_yag_g', 'karbonhidrat_g', 'seker_g', 'lif_g',
       'protein_g', 'tuz_g', 'alkol_yuzde', 'meyve_sebze_baklagil_yuzde',
       'birim', 'kategori_listesi', 'etiketler_listesi'],
      dtype='object')