In [16]:
import pandas as pd
pd.set_option('display.max_rows', None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [17]:
def clean_quantity(row):
    if pd.isna(row) or row == 'NaN':
        return None, None
    
    # Virgülü noktaya çevir (1,5 -> 1.5)
    row = str(row).replace(',', '.')
    
    # Regex ile sayısal kısmı ve birimi ayır
    # İlk sayısal grubu (ondalık dahil) ve sonrasındaki harf grubunu yakalar
    match = re.search(r"(\d+\.?\d*)\s*([a-zA-Zğüşıöç]+)?", row, re.IGNORECASE)
    
    if match:
        value = match.group(1)
        unit = match.group(2).lower() if match.group(2) else None
        
        # Birim standardizasyonu
        unit_map = {
            'ml': 'ml', 'l': 'l', 'g': 'g', 'kg': 'kg', 
            'grammes': 'g', 'gr': 'g', 'cl': 'cl'
        }
        unit = unit_map.get(unit, unit)
        
        return float(value), unit
    return None, None

def clean_categories(text):
    if pd.isna(text):
        return []
    
    # 1. Adım: Virgülleri ve boşlukları temizle
    # Virgüllere göre böl, her parçanın başındaki/sonundaki boşluğu sil
    parts = [part.strip() for part in text.split(',')]
    
    # 2. Adım: Sadece içi dolu olan (boş olmayan) kelimeleri tut
    clean_list = [p for p in parts if p and p != '']
    
    return clean_list

In [18]:
data = pd.read_csv('data/grade_b.csv')

In [19]:
data.head()

,url,barkod,urun_adi,miktar,ambalaj,markalar,kategoriler,etiketler,mensei,uretim_yerleri,...,nutriscore_puan,ns_negatif_puan,ns_pozitif_puan,ns_enerji_puan,ns_seker_puan,ns_doymus_yag_puan,ns_tuz_puan,ns_protein_puan,ns_lif_puan,ns_meyve_sebze_baklagil_puan
0,https://world.openfoodfacts.org/product/611126...,6111266962187,Lait – Jaouda – 450 ml,450 ml,NaN,Jaouda,"Dairies, ,, Meals, ,, Milks (liquid and powder...",NaN,NaN,NaN,...,-3,4,7,3.0,0,0.0,1,7.0,0,0
1,https://world.openfoodfacts.org/product/611124...,6111242101180,uht jaouda 1L – 1L,1L,"Multilayer-composite, ,, Tetra Pak",Jaouda,"Dairies, ,, Milks (liquid and powder), ,, Milk...",No gluten,NaN,NaN,...,-1,5,6,5.0,0,0.0,0,6.0,0,0
2,https://world.openfoodfacts.org/product/611103...,6111032009665,Salim – 470 ml,470 ml,NaN,Salim,"Dairies, ,, Milks (liquid and powder), ,, Milk...",No gluten,NaN,NaN,...,-3,3,6,3.0,0,0.0,0,6.0,0,0
3,https://world.openfoodfacts.org/product/611124...,6111242100206,Yaourt nature – Jaouda – 110 g,110 g,NaN,Jaouda,"Dairies, ,, Fermented foods, ,, Fermented milk...",NaN,NaN,Maroc,...,1,2,1,0.0,0,2.0,0,1.0,0,0
4,https://world.openfoodfacts.org/product/611125...,6111252421582,"اكوافينا – pepsi – 1,5l","1,5l",NaN,pepsi,"Beverages and beverages preparations, ,, Bever...",NaN,NaN,NaN,...,0,0,0,0.0,0,0.0,0,0.0,0,0

In [ ]:
data["urun_bilgisi"] = data["urun_adi"].str.split("–").str[0].str.strip()

data[['miktar', 'birim']] = data['miktar'].apply(
    lambda x: pd.Series(clean_quantity(x))
)

data['kategori_listesi'] = data['kategoriler'].apply(clean_categories)
data['etiketler_listesi'] = data['etiketler'].apply(clean_categories)

data['alerjenler'] = data['alerjenler'].apply(clean_categories)
data['eser_miktarlar'] = data['eser_miktarlar'].apply(lambda x: [item.strip() for item in str(x).split(',')] if pd.notna(x) else [])

data['markalar'] = data['markalar'].apply(lambda x: str(x).split(',')[0].strip() if pd.notnull(x) else x)

In [21]:
data[["miktar","birim"]].head()

   miktar birim
0   450.0    ml
1     1.0     l
2   470.0    ml
3   110.0     g
4     1.5     l

In [22]:
data.drop(columns=["url","urun_adi","kategoriler","etiketler","ambalaj","mensei","uretim_yerleri","satildigi_ulkeler","icerik_metni"], inplace=True)

In [23]:
data["etiketler_listesi"].head(20)

0                                                    []
1                                           [No gluten]
2                                           [No gluten]
3                                                    []
4                                                    []
5     [No artificial flavors, No preservatives, Gree...
6     [Low or no salt, Organic, Vegetarian, Certifie...
7     [Vegetarian, Source of fibre, High fibres, No ...
8     [Low or no fat, Low or no sugar, Vegetarian, L...
9     [Low or no sugar, Vegetarian, Vegan, No added ...
10    [No gluten, Organic, Catalan Council of Organi...
11    [Low or no sugar, Low sugar, Enriched with vit...
12                                              [Halal]
13    [No preservatives, Source of fibre, High fibre...
14    [Low or no fat, Pasteurized, Source of protein...
15                                          [No gluten]
16    [Low or no sugar, Vegetarian, Source of fibre,...
17                                                   []
18    [Made in France, Nutriscore, Nutriscore Grade ...
19    [Low or no sugar, Vegetarian, Organic, Certifi...
Name: etiketler_listesi, dtype: object

In [24]:
for column in data.columns:
    unique_values = data[column].astype(str).unique()
    unique_values_str = sorted(list(unique_values))
    n = 10
    displayed_values = unique_values_str[:n]
    print(f"{column} ({len(unique_values_str)}): {displayed_values}{' ...' if len(unique_values_str) > n else ''}")

barkod (155): ['20002183', '20004132', '20171841', '20267605', '3019081241216', '3023290030547', '3029330004240', '3029330022428', '3029330069898', '3029330071280'] ...
miktar (56): ['0.5', '0.7', '1.0', '1.5', '100.0', '1000.0', '110.0', '116.0', '120.0', '130.0'] ...
markalar (102): ['ALHORRA', 'Albane', 'Alesto', 'Alpro', 'Aquafina', 'Baresa', 'Bjorg', 'Blini', 'Brets', 'Briau'] ...
alerjenler (28): ["['Celery', 'Gluten', 'Soybeans']", "['Celery', 'Gluten']", "['Celery']", "['Eggs', 'Gluten', 'Milk', 'Soybeans']", "['Fish', 'Milk', 'Sesame seeds']", "['Fish', 'Soybeans']", "['Fish', 'Sulphur dioxide and sulphites']", "['Fish']", "['Gluten', 'Milk', 'Soybeans']", "['Gluten', 'Milk', 'fr:avoine']"] ...
eser_miktarlar (51): ["['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Gluten', 'Lupin', 'Milk', 'Molluscs', 'Mustard', 'Soybeans']", "['Celery', 'Crustaceans', 'Eggs', 'Fish', 'Mustard']", "['Celery', 'Crustaceans', 'Gluten', 'Molluscs', 'Mustard', 'Nuts', 'Peanuts', 'Sesame seeds', 'Soybeans']", "['Celery', 'Eggs', 'Gluten', 'Lupin', 'Milk', 'Nuts', 'Sesame seeds', 'Soybeans']", "['Celery', 'Eggs', 'Lupin', 'Milk', 'Mustard', 'Nuts', 'Sesame seeds', 'Soybeans']", "['Celery', 'Eggs', 'Milk', 'Mustard', 'Nuts', 'Sesame seeds']", "['Celery', 'Eggs', 'Milk', 'Mustard', 'Soybeans']", "['Celery', 'Lupin', 'Milk', 'Mustard', 'Nuts', 'Sesame seeds', 'Soybeans']", "['Celery', 'Mustard', 'Sesame seeds', 'Soybeans']", "['Celery', 'Nuts', 'Sesame seeds', 'Soybeans']"] ...
icerik_sayisi (29): ['1', '10', '11', '12', '13', '14', '15', '16', '17', '18'] ...
nutriscore_notu (2): ['B', 'C']
nova_grubu (5): ['1.0', '2.0', '3.0', '4.0', 'nan']
yesil_skor_notu (6): ['A', 'B', 'C', 'D', 'E', 'nan']
palmiye_yagi_icermez (3): ['False', 'True', 'nan']
vejetaryen (3): ['False', 'True', 'nan']
vegan_durumu (3): ['maybe', 'no', 'yes']
yag_seviyesi (4): ['high', 'low', 'moderate', 'nan']
doymus_yag_seviyesi (4): ['high', 'low', 'moderate', 'nan']
seker_seviyesi (4): ['high', 'low', 'moderate', 'nan']
tuz_seviyesi (4): ['high', 'low', 'moderate', 'nan']
enerji_kj (132): ['0.0', '1003.6', '1006.4', '102.0', '1020.0', '1037.6', '1038.0', '1053.0', '1056.0', '1064.0'] ...
enerji_kcal (114): ['0.0', '1.0', '100.0', '103.0', '111.0', '112.0', '115.0', '14.0', '148.0', '15.0'] ...
yag_g (78): ['0.0', '0.1', '0.188518', '0.2', '0.3', '0.333333333333333', '0.337349397590361', '0.4', '0.5', '0.7'] ...
doymus_yag_g (57): ['0.0', '0.01', '0.013', '0.0481927710843374', '0.0666666666666667', '0.1', '0.109142', '0.2', '0.3', '0.4'] ...
karbonhidrat_g (86): ['0.0', '0.1', '0.25', '0.5', '0.6', '0.7', '0.8', '0.9', '1.6', '11.8'] ...
seker_g (52): ['0.0', '0.1', '0.18588', '0.5', '0.599264705882353', '0.6', '0.7', '0.8', '1.1', '1.5'] ...
lif_g (58): ['0.0', '0.08367', '0.1', '0.2', '0.3', '0.4', '0.5', '0.57', '0.9', '1.7'] ...
protein_g (79): ['0.0', '0.05', '0.1', '0.12', '0.25', '0.333333333333333', '0.38454', '0.5', '0.6', '0.7'] ...
tuz_g (70): ['0.0', '0.0002', '0.0025', '0.0063', '0.0066666666666666', '0.01', '0.012', '0.013', '0.02', '0.03'] ...
sodyum_g (67): ['0.0', '0.001', '0.0026666666666666', '0.004', '0.0052', '0.008', '0.012', '0.02', '0.0236', '0.03'] ...
alkol_yuzde (7): ['0.0', '17.0', '22.0', '24.0', '26.0', '88.0', 'nan']
meyve_sebze_baklagil_yuzde (18): ['0.0', '0.0394775390625001', '0.0402777777777743', '0.919628906249997', '1.775', '14.5', '19.725', '2.2', '41.4018758417509', '5.125'] ...
nutriscore_puan (10): ['-1', '-2', '-3', '-4', '-5', '0', '1', '2', '3', '4']
ns_negatif_puan (13): ['0', '1', '10', '11', '14', '2', '3', '4', '5', '6'] ...
ns_pozitif_puan (12): ['0', '1', '10', '12', '2', '3', '4', '5', '6', '7'] ...
ns_enerji_puan (9): ['0.0', '1.0', '10.0', '2.0', '3.0', '4.0', '5.0', '7.0', 'nan']
ns_seker_puan (7): ['0', '1', '2', '3', '4', '5', '6']
ns_doymus_yag_puan (5): ['0.0', '1.0', '2.0', '3.0', 'nan']
ns_tuz_puan (9): ['0', '1', '2', '3', '4', '5', '6', '7', '8']
ns_protein_puan (9): ['0.0', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', 'nan']
ns_lif_puan (6): ['0', '1', '2', '3', '4', '5']
ns_meyve_sebze_baklagil_puan (5): ['0', '1', '2', '4', '5']
urun_bilgisi (155): ['100% mie Complet-Volkoren', 'Albane', 'Almond Drink', 'Amande', 'Aquafina 50cl', 'Atun', 'Atún con tomate', 'Avoine sans sucres', 'BRANDADE DE MORUE', 'Blanc de Poulet Doré au Four'] ...
birim (9): ['None', 'cl', 'g', 'kg', 'l', 'ml', 'nan', 'unknown', 'x']
kategori_listesi (139): ["['Aliments et boissons à base de végétaux', 'Boissons', 'Boissons aux fruits', 'Boissons avec sucre ajouté', 'Boissons plates aux fruits', 'Boissons sans alcool', 'Boissons à base de végétaux']", "['Beverages and beverages preparations', 'Beverages', 'Beverage preparations', 'Syrups', 'Flavoured syrups']", "['Beverages and beverages preparations', 'Beverages', 'Dairies', 'Fermented foods', 'Fermented milk products', 'Desserts', 'Dairy desserts', 'Dairy drinks', 'Fermented dairy desserts', 'Fermented drinks', 'Fermented milk drinks', 'Kefir yogurts', 'Kefir']", "['Beverages and beverages preparations', 'Beverages', 'Dairies', 'Fermented foods', 'Fermented milk products', 'Desserts', 'Dairy desserts', 'Dairy drinks', 'Fermented dairy desserts', 'Fermented drinks', 'Fermented milk drinks', 'Yogurts', 'Kefir']", "['Beverages and beverages preparations', 'Beverages', 'Dairies', 'Fermented foods', 'Fermented milk products', 'Milks (liquid and powder)', 'Dairy drinks', 'Fermented drinks', 'Milks', 'Fermented milk drinks', 'Plain fermented skimmed milk drink']", "['Beverages and beverages preparations', 'Beverages', 'Dairies', 'Spreads', 'Spreadable fats', 'Milkfat']", "['Beverages and beverages preparations', 'Beverages', 'Waters', 'Non-alcoholic beverages']", "['Beverages and beverages preparations', 'Beverages', 'Waters', 'Table waters']", "['Beverages and beverages preparations', 'Beverages', 'Waters', 'Unsweetened beverages', 'Table waters']", "['Beverages and beverages preparations', 'Plant-based foods and beverages', 'Beverages', 'Dairy substitutes', 'Milk substitutes', 'Plant-based beverages', 'Plant-based milk alternatives', 'Pasteurised products']"] ...
etiketler_listesi (123): ["['Contains alcohol', 'No palm oil', 'Nutriscore', 'Nutriscore Grade B', 'Triman']", "['Dolphin Safe', 'Natural source of Oméga 3']", "['FSC', 'FSC Mix']", "['Fair trade', 'Made in France', 'Nutriscore', 'Nutriscore Grade A', 'Agri-Éthique France', 'fr:Électricité verte']", "['Fair trade', 'Organic', 'Certified by Ecocert', 'EU Organic', 'Non-EU Agriculture', '1% for the planet', 'EU Agriculture', 'EU/non-EU Agriculture', 'Fair-Trade Organic', 'FR-BIO-01', 'Made in France', 'Nutriscore', 'Nutriscore Grade A', 'AB Agriculture Biologique', 'Agri-Éthique France', 'fr:Farine de blé français', 'fr:Local']", "['Fair trade', 'Vegetarian', 'Green Dot', 'Nutriscore', 'Nutriscore Grade A', 'Agri-Éthique France', 'Triman', 'fr:Emballage recyclable', 'fr:Fabriqué en Normandie']", "['French milk', 'Green Dot', 'No lactose', 'Enriched-wih-vitamins', 'fr:Enricĉ']", "['French milk', 'High in calcium', 'Nutriscore', 'Nutriscore Grade B', 'Triman', 'fr:Sante-des-os', 'fr:Systeme-immunitaire']", "['French milk', 'Nutriscore', 'Nutriscore Grade A', 'Renforce-en-vitamine-d', 'Source-de-10-vitamines']", "['Green Dot', 'No added sugar', 'No caffeine', 'Nutriscore', 'Nutriscore Grade A', 'Triman']"] ...

In [25]:
data["palmiye_yagi_icermez"].value_counts()

palmiye_yagi_icermez
True     128
False     24
Name: count, dtype: int64

In [26]:
data.isnull().mean() * 100

barkod                           0.000000
miktar                           3.870968
markalar                         1.290323
alerjenler                       0.000000
eser_miktarlar                   0.000000
icerik_sayisi                    0.000000
nutriscore_notu                  0.000000
nova_grubu                      11.612903
yesil_skor_notu                 12.258065
palmiye_yagi_icermez             1.935484
vejetaryen                      14.838710
vegan_durumu                     0.000000
yag_seviyesi                     0.645161
doymus_yag_seviyesi              0.645161
seker_seviyesi                   0.645161
tuz_seviyesi                     0.645161
enerji_kj                        0.000000
enerji_kcal                      0.000000
yag_g                            0.000000
doymus_yag_g                     0.000000
karbonhidrat_g                   1.290323
seker_g                          0.000000
lif_g                           27.741935
protein_g                        0.000000
tuz_g                            0.000000
sodyum_g                         3.225806
alkol_yuzde                     82.580645
meyve_sebze_baklagil_yuzde      60.645161
nutriscore_puan                  0.000000
ns_negatif_puan                  0.000000
ns_pozitif_puan                  0.000000
ns_enerji_puan                  12.903226
ns_seker_puan                    0.000000
ns_doymus_yag_puan              12.903226
ns_tuz_puan                      0.000000
ns_protein_puan                  2.580645
ns_lif_puan                      0.000000
ns_meyve_sebze_baklagil_puan     0.000000
urun_bilgisi                     0.000000
birim                            5.806452
kategori_listesi                 0.000000
etiketler_listesi                0.000000
dtype: float64

In [27]:
data.to_csv('data/cleaned_food_data.csv', index=False)

In [28]:
data.columns

Index(['barkod', 'miktar', 'markalar', 'alerjenler', 'eser_miktarlar',
       'icerik_sayisi', 'nutriscore_notu', 'nova_grubu', 'yesil_skor_notu',
       'palmiye_yagi_icermez', 'vejetaryen', 'vegan_durumu', 'yag_seviyesi',
       'doymus_yag_seviyesi', 'seker_seviyesi', 'tuz_seviyesi', 'enerji_kj',
       'enerji_kcal', 'yag_g', 'doymus_yag_g', 'karbonhidrat_g', 'seker_g',
       'lif_g', 'protein_g', 'tuz_g', 'sodyum_g', 'alkol_yuzde',
       'meyve_sebze_baklagil_yuzde', 'nutriscore_puan', 'ns_negatif_puan',
       'ns_pozitif_puan', 'ns_enerji_puan', 'ns_seker_puan',
       'ns_doymus_yag_puan', 'ns_tuz_puan', 'ns_protein_puan', 'ns_lif_puan',
       'ns_meyve_sebze_baklagil_puan', 'urun_bilgisi', 'birim',
       'kategori_listesi', 'etiketler_listesi'],
      dtype='object')